version: '3.9'

services:
    ugc:
        build:
            context: ./ugc
            dockerfile: Dockerfile
        env_file:
            - .env
        expose:
            - ${APP_PORT}
        depends_on:
            - broker
            - nginx-ugc
            - clickhouse-node1
            - clickhouse-node2
            - clickhouse-node3
            - clickhouse-node4
            - mongo_db
        networks:
            custom_network:

    nginx-ugc:
        image: nginx:1.23.3
        restart: always
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
        networks:
            custom_network:
        ports:
            - ${NGINX_PORT}:${NGINX_PORT}

    mongo_db:
        image: mongo:4.4.20-rc0-focal
        restart: always
        expose:
            - ${MONGO_PORT}
        environment:
            MONGO_INITDB_DATABASE: ${MONGO_DB}
        volumes:
            - ./mongo:/docker-entrypoint-initdb.d
        ports:
            - ${MONGO_PORT}:${MONGO_PORT}
        networks:
            custom_network:

    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        hostname: zookeeper
        container_name: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        expose:
            - ${ZOOKEEPER_PORT}
        networks:
            custom_network:

    broker:
        image: confluentinc/cp-kafka:latest
        hostname: broker
        container_name: broker
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_ZOOKEEPER_CONNECT=${ZOOKEEPER_DSN}
            - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
        depends_on:
            - zookeeper
        expose:
            - ${KAFKA_PORT}
        networks:
            custom_network:

    clickhouse-node1:
        image: yandex/clickhouse-server:latest
        container_name: clickhouse-node1
        hostname: clickhouse-node1
        env_file:
            - .env
        expose:
            - ${CLICKHOUSE_PORT_1}
            - ${CLICKHOUSE_PORT_2}
        volumes:
            - ./clickhouse/data/node1:/etc/clickhouse-server
            - ./clickhouse/init_db/init_shard1.sql:/docker-entrypoint-initdb.d/init.sql
        depends_on:
            - zookeeper
        networks:
            custom_network:

    clickhouse-node2:
        image: yandex/clickhouse-server:latest
        container_name: clickhouse-node2
        hostname: clickhouse-node2
        volumes:
            - ./clickhouse/data/node2:/etc/clickhouse-server
        depends_on:
            - zookeeper
        networks:
            custom_network:

    clickhouse-node3:
        image: yandex/clickhouse-server:latest
        container_name: clickhouse-node3
        hostname: clickhouse-node3
        env_file:
            - .env
        expose:
            - ${CLICKHOUSE_PORT_3}
            - ${CLICKHOUSE_PORT_4}
        volumes:
            - ./clickhouse/data/node3:/etc/clickhouse-server
            - ./clickhouse/init_db/init_shard2.sql:/docker-entrypoint-initdb.d/init.sql
        depends_on:
            - zookeeper
        networks:
            custom_network:


    clickhouse-node4:
        image: yandex/clickhouse-server:latest
        container_name: clickhouse-node4
        hostname: clickhouse-node4
        volumes:
            - ./clickhouse/data/node4:/etc/clickhouse-server
        depends_on:
            - zookeeper
        networks:
            custom_network:

networks:
    custom_network:
        external: True
