{
    "openapi": "3.0.2",
    "info": {
        "title": "ugc",
        "description": "User movie progress view",
        "version": "1.0.0"
    },
    "paths": {
        "/api/v1/<{movie_id}:UUID>/bookmark": {
            "post": {
                "tags": [
                    "bookmark"
                ],
                "summary": "Add movie to bookmarks",
                "description": "Add specific movie to bookmarks",
                "operationId": "add_bookmark_api_v1___movie_id__UUID__bookmark_post",
                "parameters": [
                    {
                        "description": "parameter - movie id",
                        "required": true,
                        "schema": {
                            "title": "movie id",
                            "type": "string",
                            "description": "parameter - movie id",
                            "format": "uuid"
                        },
                        "name": "movie_id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Validation Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/HTTPValidationError"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "JWTBearerRemoteGrpc": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "bookmark"
                ],
                "summary": "Delete movie from bookmarks",
                "description": "Delete specific movie from bookmarks",
                "operationId": "delete_bookmark_api_v1___movie_id__UUID__bookmark_delete",
                "parameters": [
                    {
                        "description": "parameter - movie id",
                        "required": true,
                        "schema": {
                            "title": "movie id",
                            "type": "string",
                            "description": "parameter - movie id",
                            "format": "uuid"
                        },
                        "name": "movie_id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Validation Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/HTTPValidationError"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "JWTBearerRemoteGrpc": []
                    }
                ]
            }
        },
        "/api/v1/<{movie_id}:UUID>/like": {
            "post": {
                "tags": [
                    "like"
                ],
                "summary": "Like movie",
                "description": "Add like to specific movie",
                "operationId": "like_api_v1___movie_id__UUID__like_post",
                "parameters": [
                    {
                        "description": "parameter - movie id",
                        "required": true,
                        "schema": {
                            "title": "movie id",
                            "type": "string",
                            "description": "parameter - movie id",
                            "format": "uuid"
                        },
                        "name": "movie_id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Validation Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/HTTPValidationError"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "JWTBearerRemoteGrpc": []
                    }
                ]
            }
        },
        "/api/v1/<{movie_id}:UUID>/dislike": {
            "post": {
                "tags": [
                    "like"
                ],
                "summary": "Dislike movie",
                "description": "Add dislike to specific movie",
                "operationId": "dislike_api_v1___movie_id__UUID__dislike_post",
                "parameters": [
                    {
                        "description": "parameter - movie id",
                        "required": true,
                        "schema": {
                            "title": "movie id",
                            "type": "string",
                            "description": "parameter - movie id",
                            "format": "uuid"
                        },
                        "name": "movie_id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Validation Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/HTTPValidationError"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "JWTBearerRemoteGrpc": []
                    }
                ]
            }
        },
        "/api/v1/<{movie_id}:UUID>/review": {
            "get": {
                "tags": [
                    "review"
                ],
                "summary": "Retrieve movie reviews",
                "description": "Retrieve specific movie reviews",
                "operationId": "retrieve_reviews_api_v1___movie_id__UUID__review_get",
                "parameters": [
                    {
                        "description": "parameter - movie id",
                        "required": true,
                        "schema": {
                            "title": "movie id",
                            "type": "string",
                            "description": "parameter - movie id",
                            "format": "uuid"
                        },
                        "name": "movie_id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "title": "Response Retrieve Reviews Api V1   Movie Id  Uuid  Review Get",
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/ReviewResponse"
                                    }
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Validation Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/HTTPValidationError"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "review"
                ],
                "summary": "Add review to movie",
                "description": "Add review to specific movie",
                "operationId": "add_review_api_v1___movie_id__UUID__review_post",
                "parameters": [
                    {
                        "description": "parameter - movie id",
                        "required": true,
                        "schema": {
                            "title": "movie id",
                            "type": "string",
                            "description": "parameter - movie id",
                            "format": "uuid"
                        },
                        "name": "movie_id",
                        "in": "path"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/ReviewRequest"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Validation Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/HTTPValidationError"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "JWTBearerRemoteGrpc": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "review"
                ],
                "summary": "Delete review from movie",
                "description": "Delete review from specific movie",
                "operationId": "delete_review_api_v1___movie_id__UUID__review_delete",
                "parameters": [
                    {
                        "description": "parameter - movie id",
                        "required": true,
                        "schema": {
                            "title": "movie id",
                            "type": "string",
                            "description": "parameter - movie id",
                            "format": "uuid"
                        },
                        "name": "movie_id",
                        "in": "path"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/ReviewRequest"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Validation Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/HTTPValidationError"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "JWTBearerRemoteGrpc": []
                    }
                ]
            }
        },
        "/api/v1/view_progress": {
            "post": {
                "tags": [
                    "view"
                ],
                "summary": "Message about watching the film",
                "description": "Message about watching the film",
                "operationId": "view_progress_api_v1_view_progress_post",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/ViewProgressRequest"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Validation Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/HTTPValidationError"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "HTTPValidationError": {
                "title": "HTTPValidationError",
                "type": "object",
                "properties": {
                    "detail": {
                        "title": "Detail",
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/ValidationError"
                        }
                    }
                }
            },
            "ReviewRequest": {
                "title": "ReviewRequest",
                "required": [
                    "review",
                    "score"
                ],
                "type": "object",
                "properties": {
                    "review": {
                        "title": "Review",
                        "maxLength": 100,
                        "type": "string"
                    },
                    "score": {
                        "title": "Score",
                        "maximum": 10.0,
                        "minimum": 0.0,
                        "type": "integer"
                    }
                },
                "description": "Review request."
            },
            "ReviewResponse": {
                "title": "ReviewResponse",
                "required": [
                    "review",
                    "score",
                    "_id"
                ],
                "type": "object",
                "properties": {
                    "review": {
                        "title": "Review",
                        "maxLength": 100,
                        "type": "string"
                    },
                    "score": {
                        "title": "Score",
                        "maximum": 10.0,
                        "minimum": 0.0,
                        "type": "integer"
                    },
                    "_id": {
                        "title": " Id",
                        "type": "string"
                    }
                },
                "description": "Review response."
            },
            "ValidationError": {
                "title": "ValidationError",
                "required": [
                    "loc",
                    "msg",
                    "type"
                ],
                "type": "object",
                "properties": {
                    "loc": {
                        "title": "Location",
                        "type": "array",
                        "items": {
                            "anyOf": [
                                {
                                    "type": "string"
                                },
                                {
                                    "type": "integer"
                                }
                            ]
                        }
                    },
                    "msg": {
                        "title": "Message",
                        "type": "string"
                    },
                    "type": {
                        "title": "Error Type",
                        "type": "string"
                    }
                }
            },
            "ViewProgressRequest": {
                "title": "ViewProgressRequest",
                "required": [
                    "movie_id",
                    "user_id",
                    "viewed_frame"
                ],
                "type": "object",
                "properties": {
                    "movie_id": {
                        "title": "Movie Id",
                        "type": "string",
                        "format": "uuid"
                    },
                    "user_id": {
                        "title": "User Id",
                        "type": "string",
                        "format": "uuid"
                    },
                    "viewed_frame": {
                        "title": "Viewed Frame",
                        "type": "integer"
                    }
                },
                "description": "View progress request body."
            }
        },
        "securitySchemes": {
            "JWTBearerRemoteGrpc": {
                "type": "http",
                "scheme": "bearer"
            }
        }
    }
}
